---
- name: Install development packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
  - git
  - cmake
  - libtool-bin
  - qt5-default         # for neovim-qt
  - python3
  - python3-pip
  # rvm's ruby deps:
  - gawk
  - g++
  - gcc
  - make
  - libc6-dev
  - libreadline6-dev
  - zlib1g-dev
  - libssl-dev
  - libyaml-dev
  - libsqlite3-dev
  - sqlite3
  - autoconf
  - libgmp-dev
  - libgdbm-dev
  - libncurses5-dev
  - automake
  - libtool
  - bison
  - pkg-config
  - libffi-dev
  - exuberant-ctags
- name: Download Go
  get_url:
    url: https://storage.googleapis.com/golang/go{{go_version}}.linux-amd64.tar.gz
    dest: /usr/local/src/go{{go_version}}.linux-amd64.tar.gz
    checksum: sha256:{{go_checksum}}
- name: Create directory for Go {{go_version}}
  file:
    path: /usr/local/go{{go_version}}
    state: directory
- name: Install Go {{go_version}}
  unarchive:
    remote_src: yes
    src: /usr/local/src/go{{go_version}}.linux-amd64.tar.gz
    dest: /usr/local/go{{go_version}}
    creates: /usr/local/go{{go_version}}/go
- name: Create symlink at /usr/local/go
  file:
    src: /usr/local/go{{go_version}}/go
    dest: /usr/local/go
    state: link
