---
- name: Install development packages
  apt:
    state: present
    name:
      - autoconf
      - automake
      - bison
      - cmake
      - cppcheck
      - exuberant-ctags
      - g++
      - gawk
      - gcc
      - gettext
      - git
      - gitk
      - imagemagick
      - jq  # json processor
      - libc6-dev
      - libffi-dev
      - libgdbm-dev
      - libgmp-dev
      - libncurses5-dev
      - libreadline6-dev
      - libsqlite3-dev
      - libssl-dev
      - libtool
      - libtool-bin
      - libyaml-dev
      - linux-perf
      - make
      - ninja-build
      - octave
      - pkg-config
      - r-base
      - r-base-dev
      - shellcheck
      - sqlite3
      - strace
      - subversion
      - unzip
      - libxml2-utils
      - yamllint
      - zlib1g-dev
- name: Download Go
  get_url:
    url: https://storage.googleapis.com/golang/go{{go_version}}.linux-amd64.tar.gz
    dest: /usr/local/src/go{{go_version}}.linux-amd64.tar.gz
    checksum: sha256:{{go_checksum}}
- name: Create directory for Go {{go_version}}
  file:
    path: /usr/local/go{{go_version}}
    state: directory
- name: Install Go {{go_version}}
  unarchive:
    remote_src: true
    src: /usr/local/src/go{{go_version}}.linux-amd64.tar.gz
    dest: /usr/local/go{{go_version}}
    creates: /usr/local/go{{go_version}}/go
- name: Create symlink at /usr/local/go
  file:
    src: /usr/local/go{{go_version}}/go
    dest: /usr/local/go
    state: link
- name: Add go to path for all users
  copy:
    content: "export PATH=$PATH:/usr/local/go/bin\n"
    dest: /etc/profile.d/gopath.sh
