---
- name: Install development packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - cmake
    - cppcheck
    - git
    - jq  # json processor
    - libtool-bin
    - python3
    - python3-cxx-dev
    - python3-pip
    - python-cxx-dev
    - qt5-default  # for neovim-qt
    - r-base
    - r-base-dev
    - yamllint
    # rvm's ruby deps:
    - autoconf
    - automake
    - bison
    - exuberant-ctags
    - g++
    - gawk
    - gcc
    - libc6-dev
    - libffi-dev
    - libgdbm-dev
    - libgmp-dev
    - libncurses5-dev
    - libreadline6-dev
    - libsqlite3-dev
    - libssl-dev
    - libtool
    - libyaml-dev
    - make
    - pkg-config
    - sqlite3
    - zlib1g-dev
- name: Download Go
  get_url:
    url: https://storage.googleapis.com/golang/go{{go_version}}.linux-amd64.tar.gz
    dest: /usr/local/src/go{{go_version}}.linux-amd64.tar.gz
    checksum: sha256:{{go_checksum}}
- name: Create directory for Go {{go_version}}
  file:
    path: /usr/local/go{{go_version}}
    state: directory
- name: Install Go {{go_version}}
  unarchive:
    remote_src: true
    src: /usr/local/src/go{{go_version}}.linux-amd64.tar.gz
    dest: /usr/local/go{{go_version}}
    creates: /usr/local/go{{go_version}}/go
- name: Create symlink at /usr/local/go
  file:
    src: /usr/local/go{{go_version}}/go
    dest: /usr/local/go
    state: link
