---
- hosts: all
  remote_user: tim
  become: true
  become_method: su
  tasks:
    - include: packages.yml
    - include: x11.yml
    - include: samba.yml
    - include: backup.yml
    - include: dev.yml
    - include: dlna.yml
    - include: database.yml
    - include: web.yml
    - include: rwtxt.yml
    - include: miniflux.yml
    - include: ddns.yml
    - include: neovim.yml
    - include: ssh.yml
    - include: redmine.yml
    - name: Configure user tim
      user:
        name: tim
        shell: /usr/bin/fish
        groups: sudo,export
        append: true
  handlers:
    - name: Restart apache
      service:
        name: apache2
        state: restarted
    - name: Restart samba
      service: name={{item}} state=restarted
      with_items:
        - smbd
        - nmbd
    - name: Restart hostapd
      service:
        name: hostapd
        state: restarted
    - name: Restart networking
      service:
        name: networking
        state: restarted
    - name: Restart minidlna
      service:
        name: minidlna
        state: restarted
    - name: Restart sshd
      service:
        name: sshd
        state: restarted
  vars_files:
    - vars.yml
    - secrets.yml
