---
- hosts: all
  remote_user: tim
  become: yes
  become_method: su
  tasks:
  - include: packages.yml
  - include: samba.yml
  - include: minecraft.yml
  - include: backup.yml
  - include: dev.yml
  - include: wifi.yml
  - include: dlna.yml
  - include: database.yml
  - name: Configure user tim
    user:
      name: tim
      shell: /usr/bin/zsh
      groups: sudo,export
      append: yes
  handlers:
    - name: Restart samba
      service: name={{item}} state=restarted
      with_items:
      - smbd
      - nmbd
      - samba-ad-dc
    - name: Restart hostapd
      service:
        name: hostapd
        state: restarted
    - name: Restart networking
      service:
        name: networking
        state: restarted
    - name: Restart minidlna
      service:
        name: minidlna
        state: restarted
  vars_files:
    - vars.yml
